# Generated by Django 3.2.7 on 2021-11-25 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_disease_medicine_medtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='company',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='disease',
            field=models.ForeignKey(default='We will update soon', on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.disease'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='type',
            field=models.ForeignKey(default='We will update soon', on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.medtype'),
        ),
        migrations.AlterField(
            model_name='medtype',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medtype',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
