# Generated by Django 3.2.7 on 2021-11-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211125_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
