# Generated by Django 3.2.7 on 2021-11-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211125_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='superCategory_name',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SuperCategory',
        ),
    ]
